### ISSUE TITLE
Encrypt password failing (-e)

### ISSUE THREAD

**Issue by NewtonChutney** [momiji/kpx#1]
In cmdline, trying to encrypt the password fails:

```PowerShell
C:\Windows\System32>kpx -e
Encrypt a password - key location is `kpx.key`
Password: ****************
panic: open kpx.key: Access is denied.

goroutine 1 [running]:
github.com/momiji/kpx.readKey()
        /home/flops/dev/kpx/password.go:30 +0xc8
github.com/momiji/kpx.createHash()
        /home/flops/dev/kpx/password.go:37 +0x65
github.com/momiji/kpx.encrypt({0xc0000adde0, 0x10})
        /home/flops/dev/kpx/password.go:42 +0x2f
github.com/momiji/kpx.encryptPassword()
        /home/flops/dev/kpx/password.go:86 +0x118
github.com/momiji/kpx.cmd()
        /home/flops/dev/kpx/main.go:263 +0x64c
github.com/momiji/kpx.Main()
        /home/flops/dev/kpx/main.go:209 +0x23b
main.main()
        /home/flops/dev/kpx/cli/main.go:6 +0xf
```

I have tried creating an empty file and retry.. but still fails

**Comment by momiji** [comment]
Hello,

Encryption requires to have a file kpx.key with the encryption key used to encrypt the password.
This file is automatically created with the key, and is located near (in the same folder as) kpx.exe binary.

So you need to be able to write a file in this folder, I guess access is denied because it fails to create this file.
This is probably due to kpx running with an account which is not allowed to write in this folder.

**Comment by NewtonChutney** [comment]
Yes, this makes perfect sense.. I was doubting the lack of the config file in the CWD being the reason..
I overlooked I was in the system directory..
Thanks!

**Comment by NewtonChutney** [comment]
Yes, this makes perfect sense.. I was doubting the lack of the config file in the CWD being the reason..
I overlooked I was in the system directory..
Thanks!

**Comment by NewtonChutney** [comment]
And I was tinkering with the multiple PAC, multiple usernames of multiple domain config..
I had a tough time at first.. But after tinkering it works.. We do need some better workflow and/or documentation.. 😅

It didn't work with:
- Listing my new proxy PAC under "proxies"
- putting the second user under "credentials" and setting the user for the PAC
- creating a rule and setting the proxy to be used..

It finally worked with:
- Listing the proxies inside the PAC under "proxies" 
- and setting the config for this proxy.. There seems to be a regex for which PAC files this proxy config is to he used.. And mentioning the realm here

This is quite a complex workflow.. 
Won't it be better to mention the realm along with the user under "credentials" and to set the user creds to be used for the whole PAC?

**Comment by NewtonChutney** [comment]
Access was denied as the curdir was in the system directory, retrying inside user dir worked as expected

**Comment by momizulie** [comment]
> And I was tinkering with the multiple PAC, multiple usernames of multiple domain config.. I had a tough time at first.. But after tinkering it works.. We do need some better workflow and/or documentation.. 😅
> 
> It didn't work with:
> 
>     * Listing my new proxy PAC under "proxies"
> 
>     * putting the second user under "credentials" and setting the user for the PAC
> 
>     * creating a rule and setting the proxy to be used..
> 
> 
> It finally worked with:
> 
>     * Listing the proxies inside the PAC under "proxies"
> 
>     * and setting the config for this proxy.. There seems to be a regex for which PAC files this proxy config is to he used.. And mentioning the realm here
> 
> 
> This is quite a complex workflow.. Won't it be better to mention the realm along with the user under "credentials" and to set the user creds to be used for the whole PAC?

Hello, didn't see this message until today, sorry.

I understand, however this is not always as simple.
At work, we do have PAC files with multiple proxies that required multiple different authentication, which is the reason why PAC needs to find the

**Comment by NewtonChutney** [comment]
Yes, I use it in work too.. instead of px/go-ntlm/alpaca
I want aware of the mechanism of how pac goes are processed..
I'm alright with how things work currently, the performance is very much noticeable vs px! 🎉
