### ISSUE TITLE
Make kerberos authentication using ccache

### ISSUE THREAD

**Issue by yolkispalkis** [momiji/kpx#2]
Entering a password and login is not always convenient
If the system is in a domain and login is configured via kerberos, it will be much more convenient.

**Comment by momiji** [comment]
This is a good idea, I need to have a look if there is a ccache compatible library for kerberos in golang.
A fast search 5mn search didn't give me any result yet, but I'll keep this in mind.

**Comment by yolkispalkis** [comment]
> This is a good idea, I need to have a look if there is a ccache compatible library for kerberos in golang. A fast search 5mn search didn't give me any result yet, but I'll keep this in mind.

https://github.com/dpotapov/go-spnego
Please take a look at this repo

**Comment by momiji** [comment]
Working on Windows now, is it enough or do you need Linux also?
If so I'll publish it soon.

**Comment by momiji** [comment]
Implemented in both Windows and Linux, but only tested on Windows so far.
No unit tests done yet, this may came in the future.
Corporate internal version also updated.
